// Generated by Selenium IDE
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class DefaultSuiteTest {
  
  private WebDriver driver;

  private Map<String, Object> vars;
  
  JavascriptExecutor js;

  private WebDriverWait wait;
  
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:\\apps\\chromedriver.exe");
    driver = new ChromeDriver();
    wait = new WebDriverWait(driver, 10);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    if(null != driver) driver.quit();
  }

  @Test
  public void clubs() {
    driver.get("http://rdomloge.entrydns.org:81/static/html/index.html");
    driver.manage().window().setSize(new Dimension(1296, 708));
    driver.findElement(By.linkText("Clubs")).click();
    wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".w3-padding-24")));
    assertThat(driver.findElement(By.cssSelector(".ng-scope > .w3-left")).getText(), is("Clubs"));
    assertThat(driver.findElement(By.cssSelector(".w3-padding-24")).getText(), is("Aldermaston"));
    assertThat(driver.findElement(By.cssSelector(".w3-border-bottom:nth-child(3) > .ng-binding")).getText(), is("Stephen Gaunt"));
    assertThat(driver.findElement(By.cssSelector(".w3-row:nth-child(3) > .w3-text-grey")).getText(), is("Secretary"));
    assertThat(driver.findElement(By.cssSelector(".w3-row:nth-child(3) span:nth-child(1)")).getText(), is("n/a"));
    assertThat(driver.findElement(By.linkText("stephen1.gaunt@gmail.com")).getText(), is("stephen1.gaunt@gmail.com"));
    {
      List<WebElement> elements = driver.findElements(By.xpath("//a[contains(@href, \'mailto:stephen1.gaunt@gmail.com\')]"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".w3-black")).click();
    driver.findElement(By.linkText("BH Pegasus")).click();
    wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".w3-container:nth-child(4) .w3-col:nth-child(1)")));
    assertThat(driver.findElement(By.cssSelector(".w3-container:nth-child(4) .w3-col:nth-child(1)")).getText(), is("Tuesdays"));
    assertThat(driver.findElement(By.cssSelector(".w3-col > .ng-binding")).getText(), is("07713899542 (Mobile)"));
    assertThat(driver.findElement(By.cssSelector(".w3-row:nth-child(2) > .w3-text-grey")).getText(), is("Chairman"));
    {
      List<WebElement> elements = driver.findElements(By.xpath("//a[contains(@href, \'unsafe:tel:07713899542\')]"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector(".w3-container:nth-child(4) > .w3-left")).getText(), is("Club nights"));
    assertThat(driver.findElement(By.cssSelector(".w3-container:nth-child(4) .w3-col:nth-child(2)")).getText(), is("Basingstoke Sports Centre"));
    assertThat(driver.findElement(By.cssSelector(".w3-container:nth-child(4) .w3-medium")).getText(), is("Basingstoke Sports Centre Festival Place Basingstoke Hants RG21 7LE"));
    assertThat(driver.findElement(By.cssSelector(".w3-container:nth-child(4) .w3-col:nth-child(4)")).getText(), is("19:40 - 22:20"));
    assertThat(driver.findElement(By.cssSelector(".w3-container:nth-child(4) .w3-col:nth-child(5)")).getText(), is("4 courts"));
    assertThat(driver.findElement(By.cssSelector(".w3-container:nth-child(5) > .w3-left")).getText(), is("Match nights"));
    assertThat(driver.findElement(By.cssSelector(".w3-container:nth-child(5) .w3-col:nth-child(1)")).getText(), is("Tuesdays"));
    assertThat(driver.findElement(By.cssSelector(".w3-container:nth-child(5) .w3-col:nth-child(2)")).getText(), is("Basingstoke Sports Centre"));
    assertThat(driver.findElement(By.cssSelector(".w3-container:nth-child(5) .w3-medium")).getText(), is("Basingstoke Sports Centre Festival Place Basingstoke Hants RG21 7LE"));
    assertThat(driver.findElement(By.cssSelector(".w3-container:nth-child(4) .w3-col:nth-child(4)")).getText(), is("19:40 - 22:20"));
    assertThat(driver.findElement(By.cssSelector(".w3-container:nth-child(4) .w3-col:nth-child(5)")).getText(), is("4 courts"));
  }

  @Test
  public void frontpage() {
    driver.get("http://rdomloge.entrydns.org:81/static/html/index.html");
    driver.manage().window().setSize(new Dimension(1296, 708));
    assertThat(driver.findElement(By.cssSelector(".ng-scope > .w3-padding-32")).getText(), is("News"));
    assertThat(driver.findElement(By.cssSelector(".w3-card:nth-child(2) .w3-xxlarge")).getText(), is("Season 2020/21 Cancelled"));
    assertThat(driver.findElement(By.cssSelector(".w3-card:nth-child(2) > .ng-isolate-scope > .w3-xlarge")).getText(), is("Season 2020/21 Cancelled"));
    assertThat(driver.findElement(By.cssSelector(".w3-card:nth-child(2) > .ng-isolate-scope > div > .ng-binding")).getText(), is("12 December 2020"));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".w3-card:nth-child(2) .ng-binding:nth-child(4)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".w3-card:nth-child(2) .ng-binding:nth-child(4).ng-hide"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".w3-card:nth-child(2) .w3-xlarge:nth-child(1)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".w3-card:nth-child(2) .ng-binding:nth-child(4).ng-hide"));
      assert(elements.size() == 0);
    }
    driver.findElement(By.cssSelector(".w3-card:nth-child(2) > .ng-isolate-scope > div > .w3-xlarge:nth-child(2)")).click();
  }
  
  @Test
  public void leaguecommittee() {
    driver.get("http://rdomloge.entrydns.org:81/static/html/index.html");
    driver.manage().window().setSize(new Dimension(1296, 708));
    driver.findElement(By.linkText("League Committee")).click();
    wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".w3-card-4:nth-child(2)")));
    assertThat(driver.findElement(By.cssSelector(".w3-padding")).getText(), is("Committee"));
    assertThat(driver.findElement(By.cssSelector(".w3-card-4:nth-child(2) > .w3-text-blue > .ng-binding")).getText(), is("Chairman"));
    assertThat(driver.findElement(By.cssSelector(".w3-card-4:nth-child(2) > .w3-container:nth-child(2) > .ng-binding:nth-child(1)")).getText(), is("Horace Mitchell"));
    assertThat(driver.findElement(By.cssSelector(".w3-card-4:nth-child(2) > .w3-container > .ng-binding:nth-child(2)")).getText(), is("Viking Badminton Club"));
    assertThat(driver.findElement(By.cssSelector(".w3-card-4:nth-child(2) h2:nth-child(1) > .ng-binding")).getText(), is("07786867718"));
    {
      List<WebElement> elements = driver.findElements(By.xpath("//a[contains(@href, \'unsafe:tel:07786867718\')]"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector(".w3-card-4:nth-child(2) h2:nth-child(2) > .ng-binding")).getText(), is("horacemitchell@virginmedia.com"));
    {
      List<WebElement> elements = driver.findElements(By.xpath("//a[contains(@href, \'mailto:horacemitchell@virginmedia.com\')]"));
      assert(elements.size() > 0);
    }
  }
  
  
}
